import { beforeEach, describe, expect, it, vi } from 'vitest';
import { api } from '../../app/api';
import { createChatSessionRepository, readSessionListCache, sessionListCacheStorageKey, writeSessionListCache } from './chatSessionRepository';
vi.mock('../../app/api', async original => ({ ...(await original<typeof import('../../app/api')>()), api: vi.fn() }));
const request=vi.mocked(api);
beforeEach(()=>{localStorage.clear();request.mockReset()});
describe('chatSessionRepository local runtime',()=>{
 it('lists sessions through local API and caches by agent id',async()=>{request.mockResolvedValue({sessions:[{id:'default'}]});const repository=createChatSessionRepository();await expect(repository.listSessions('agent/name')).resolves.toEqual([{id:'default'}]);expect(request).toHaveBeenCalledWith('/api/sessions?agentId=agent%2Fname');expect(readSessionListCache('agent/name')).toEqual([{id:'default'}])});
 it('loads and resets sessions using encoded path identifiers',async()=>{request.mockResolvedValueOnce({session:{id:'child/session',turns:[]}}).mockResolvedValueOnce(undefined);const repository=createChatSessionRepository();await expect(repository.loadSession('agent/name','child/session')).resolves.toEqual({id:'child/session',turns:[]});await repository.resetSession('agent/name','child/session');expect(request).toHaveBeenNthCalledWith(1,'/api/sessions/child%2Fsession?agentId=agent%2Fname');expect(request).toHaveBeenNthCalledWith(2,'/api/sessions/child%2Fsession/reset?agentId=agent%2Fname',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})});
 it('propagates failures without replacing cached session list',async()=>{writeSessionListCache('agent',[{id:'cached'}]);request.mockRejectedValueOnce(new Error('offline'));await expect(createChatSessionRepository().listSessions('agent')).rejects.toThrow('offline');expect(readSessionListCache('agent')).toEqual([{id:'cached'}])});
});
describe('session list cache',()=>{it('rejects malformed storage',()=>{localStorage.setItem(sessionListCacheStorageKey,'{broken');expect(readSessionListCache('agent')).toBeNull()});it('retains only sixteen most recently written agents',()=>{for(let i=0;i<17;i++)writeSessionListCache(`agent-${i}`,[{id:'default'}]);const stored=JSON.parse(localStorage.getItem(sessionListCacheStorageKey)??'{}');expect(Object.keys(stored.value)).toHaveLength(16);expect(stored.value).not.toHaveProperty('agent-0')})});
