import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { Archive } from './ArchivePage';
import { loadModArchives, modsChangedEvent } from '../../app/modPanels';
vi.mock('../../app/modPanels', () => ({ loadModArchives: vi.fn(), modsChangedEvent: 'burrow:mods-changed' }));
vi.mock('../mods/ModArchiveHost', () => ({ ModArchiveHost: ({ date }: { date: string }) => <div data-testid="mod-date">{date || 'all dates'}</div> }));
vi.mock('./archiveRepository', () => ({ archiveRepository: { listContinuityCards: async () => [], listDreams: async () => [], listSessions: async () => [] } }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it('discovers Archive contributions, passes calendar date and removes disabled destinations', async () => {
  vi.mocked(loadModArchives).mockResolvedValue([{ modId: 'fixture', name: 'Fixture archive', archiveUrl: '/api/mods/fixture/ui/archive.js' }]);
  render(<Archive agents={[]} />);
  fireEvent.click(await screen.findByRole('button', { name: 'Fixture archive' }));
  expect(screen.getByTestId('mod-date').textContent).toBe('all dates');
  const day = screen.getAllByRole('button').find(button => /^\d{4}-\d{2}-01$/.test(button.getAttribute('aria-label') || ''))!;
  fireEvent.click(day); expect(screen.getByTestId('mod-date').textContent).toBe(day.getAttribute('aria-label'));
  fireEvent.click(screen.getByRole('button', { name: 'All dates' })); expect(screen.getByTestId('mod-date').textContent).toBe('all dates');
  vi.mocked(loadModArchives).mockResolvedValue([]); window.dispatchEvent(new Event(modsChangedEvent));
  await waitFor(() => expect(screen.queryByRole('button', { name: 'Fixture archive' })).toBeNull());
  expect(screen.queryByTestId('mod-date')).toBeNull();
});
