import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { apiForTarget } from '../../app/api';
import { AgentProfileDocuments } from './AgentProfileDocuments';
import { AgentMcpTools } from './AgentMcpTools';
import { AgentDreams } from './AgentDreams';
vi.mock('../../app/api', () => ({ apiForTarget: vi.fn() }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
const targets = [{ id: 'local', name: 'Local', baseUrl: '', enabled: true }];
it.each(['profiles', 'grants', 'dreams'])('FE005 %s rejects failed-owner writes then retries successfully', async kind => {
 let fail = true;
 const calls = vi.mocked(apiForTarget);
 calls.mockImplementation(async (_target, path, init) => {
  if (init?.method === 'PUT') return { settings: { enabled: false, cron: '0 4 * * *', timezone: null, prompt: 'B' } };
  if (path.includes('/B/') && fail) throw new Error('B unavailable');
  if (path.includes('profile-documents')) return { documents: [{ kind: 'SOUL', markdown: path.includes('/A/') ? 'A secret' : 'B own' }] };
  if (path.includes('mcp-connections')) return { connections: [{ id: 'server', name: 'Server', transport: 'http', tools: [{ name: 'read' }] }] };
  if (path.includes('mcp-tools')) return { tools: [{ connectionId: 'server', toolName: 'read', enabled: true }] };
  if (path.includes('dream-settings')) return { settings: { enabled: false, cron: '0 4 * * *', timezone: null, prompt: path.includes('/A/') ? 'A secret' : 'B own' } };
  return { receipts: [] };
 });
 const view = (agentId: string) => kind === 'profiles' ? <AgentProfileDocuments agentId={agentId} targets={targets} /> : kind === 'grants' ? <AgentMcpTools agentId={agentId} targets={targets} /> : <AgentDreams agentId={agentId} targets={targets} savedProviders={[]} />;
 const { rerender } = render(view('A'));
 await waitFor(() => expect(screen.getByRole('button', { name: /Save/ }).hasAttribute('disabled')).toBe(false));
 rerender(view('B'));
 await waitFor(() => expect(screen.getAllByText(/B unavailable/).length).toBeGreaterThan(0));
 const save = screen.getByRole('button', { name: /Save/ });
 expect(save.hasAttribute('disabled')).toBe(true);
 fireEvent.click(save);
 expect(calls.mock.calls.filter(c => c[2]?.method === 'PUT')).toHaveLength(0);
 expect(screen.queryByDisplayValue('A secret')).toBeNull();
 fail = false;
 fireEvent.click(screen.getByRole('button', { name: /Retry/ }));
 await waitFor(() => expect(screen.getByRole('button', { name: /Save/ }).hasAttribute('disabled')).toBe(false));
 fireEvent.click(screen.getByRole('button', { name: /Save/ }));
 await waitFor(() => expect(calls.mock.calls.filter(c => c[2]?.method === 'PUT')).toHaveLength(1));
 const write = calls.mock.calls.find(c => c[2]?.method === 'PUT')!;
 expect(write[1]).toContain('/B/');
 expect(write[2]?.body).not.toContain('A secret');
});
