import { useCallback, useEffect, useState } from 'react';
import { Field, SettingSection } from './SettingsPrimitives';
import { loadModManagement, modLifecyclePath, modManagementAction, type ModRecord, type ModSource, type NormalizedModManagement } from './modManagementApi';

function actionLabel(mod: ModRecord) { return mod.status === 'installed' && mod.updateAvailable ? 'Update' : 'Install'; }

export function ModsSettings() {
  const [state, setState] = useState<NormalizedModManagement>({ mods: [], sources: [], restartRequired: false });
  const [sourceUrl, setSourceUrl] = useState('');
  const [version, setVersion] = useState('');
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setError(null); try { setState(await loadModManagement()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load mod management.'); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (key: string, path: string, init?: RequestInit) => { setBusy(key); setError(null); try { const result = await modManagementAction(path, init); const next = await loadModManagement(); setState(next); if (result && typeof result === 'object' && 'restartRequired' in result && result.restartRequired === true) setState(current => ({ ...current, restartRequired: true })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Mod operation failed.'); } finally { setBusy(null); } };
  const install = (mod: ModRecord) => { const selectedVersion = version.trim(); setVersion(''); void run(mod.id, modLifecyclePath(mod.id, 'install'), { method: 'POST', body: JSON.stringify(selectedVersion ? { version: selectedVersion } : {}) }); };
  const addSource = () => { const url = sourceUrl.trim(); if (!url) return; void run('source', '/api/mod-management/sources', { method: 'POST', body: JSON.stringify({ url }) }).then(() => setSourceUrl('')); };
  return <div className="mod-management-settings">
    <header className="mods-settings-header"><div><span className="eyebrow">CORE MANAGEMENT</span><h1>Mods</h1><p className="settings-description">Manage the extensions that shape this Burrow installation.</p></div><button className="secondary" type="button" disabled={busy !== null} onClick={() => void run('refresh', '/api/mod-management/refresh', { method: 'POST', body: '{}' })}>{busy === 'refresh' ? 'Refreshing…' : 'Refresh'}</button></header>
    {error && <p className="settings-request-error" role="alert">{error}</p>}
    {state.restartRequired && <aside className="mod-restart-notice" role="status"><strong>Restart required</strong><span>Core needs a restart for the latest mod changes to take effect.</span></aside>}
    <SettingSection title="Installed and available mods"><p className="settings-description">Install updates, toggle availability, or remove any mod, including Core mods.</p>{state.mods.length === 0 ? <p className="settings-empty">No mods available.</p> : <div className="mod-management-list">{state.mods.map(mod => { const installed = mod.status === 'installed'; const actionBusy = busy === mod.id; return <article className="mod-management-card" key={mod.id}><div className="mod-management-card-main"><div className="mod-card-heading"><strong>{mod.name}</strong>{mod.system && <span className="mod-badge">Core</span>}</div><small>{mod.id}</small><div className="mod-management-meta"><span className={`mod-status ${installed ? 'installed' : ''}`}>{mod.status || 'available'}</span>{installed && <span className={`mod-status ${mod.enabled ? 'enabled' : 'disabled'}`}>{mod.enabled ? 'Enabled' : 'Disabled'}</span>}{mod.version && <span>Current {mod.version}</span>}{mod.latestVersion && <span>Latest {mod.latestVersion}</span>}</div>{mod.reason && <p>{mod.reason}</p>}</div><div className="mod-management-actions"><button className={installed ? 'secondary' : 'primary'} type="button" disabled={busy !== null || (installed ? !mod.updateAvailable : mod.canInstall === false)} onClick={() => install(mod)}>{actionBusy ? 'Working…' : actionLabel(mod)}</button>{installed && <><button className="secondary" type="button" disabled={busy !== null} onClick={() => void run(mod.id, modLifecyclePath(mod.id, mod.enabled ? 'disable' : 'enable'), { method: 'POST' })}>{actionBusy ? 'Working…' : mod.enabled ? 'Disable' : 'Enable'}</button><button className="danger" type="button" disabled={busy !== null} onClick={() => void run(mod.id, modLifecyclePath(mod.id, 'uninstall'), { method: 'POST' })}>{actionBusy ? 'Working…' : 'Uninstall'}</button></>}</div></article>; })}</div>}</SettingSection>
    <SettingSection title="Install a specific version"><p className="settings-description">Optionally choose a version for the next install or update. Leave blank to use the source default.</p><div className="mod-version-form"><Field label="Version"><input value={version} onChange={event => setVersion(event.target.value)} placeholder="e.g. 1.2.3" /></Field></div></SettingSection>
    <SettingSection title="Mod sources"><p className="settings-description">Sources are checked by Core for available mod releases.</p><div className="mod-source-add"><Field label="Source URL"><input value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} placeholder="https://example.invalid/mods.json" /></Field><button className="primary" type="button" disabled={!sourceUrl.trim() || busy !== null} onClick={addSource}>{busy === 'source' ? 'Adding…' : 'Add source'}</button></div>{state.sources.length === 0 ? <p className="settings-empty">No custom sources configured.</p> : <div className="mod-source-list">{state.sources.map((source: ModSource) => <div className="mod-source-card" key={source.id}><div><strong>{source.url}</strong><small>{source.status || 'Unknown'}{source.lastCheckedAt ? ` · Checked ${source.lastCheckedAt}` : ''}{source.error ? ` · ${source.error}` : ''}</small></div><button className="danger" type="button" disabled={busy !== null} onClick={() => void run(source.id, `/api/mod-management/sources/${encodeURIComponent(source.id)}`, { method: 'DELETE' })}>Remove</button></div>)}</div>}</SettingSection>
  </div>;
}
