import { useCallback, useEffect, useState } from 'react';
import { Field, SettingSection } from './SettingsPrimitives';
import { loadModManagement, modLifecyclePath, modManagementAction, type ModRecord, type ModSource } from './modManagementApi';

function actionLabel(mod: ModRecord) { return mod.status === 'installed' && mod.updateAvailable ? 'Update' : mod.status === 'installed' ? 'Installed' : 'Install'; }

export function ModsSettings() {
  const [mods, setMods] = useState<ModRecord[]>([]);
  const [sources, setSources] = useState<ModSource[]>([]);
  const [sourceUrl, setSourceUrl] = useState('');
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setError(null); try { const state = await loadModManagement(); setMods(state.mods); setSources(state.sources); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load mod management.'); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (key: string, path: string, init?: RequestInit) => { setBusy(key); setError(null); try { await modManagementAction(path, init); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Mod operation failed.'); } finally { setBusy(null); } };
  const addSource = () => { const url = sourceUrl.trim(); if (!url) return; void run('source', '/api/mod-management/sources', { method: 'POST', body: JSON.stringify({ url }) }).then(() => setSourceUrl('')); };
  return <div className="mod-management-settings">
    <SettingSection title="Mods"><p className="settings-description">Install, update, enable, disable, and remove Burrow mods managed by Core.</p>{error && <p className="settings-request-error" role="alert">{error}</p>}
      {mods.length === 0 ? <p className="settings-empty">No mods available.</p> : <div className="mod-management-list">{mods.map(mod => { const installed = mod.status === 'installed'; const actionBusy = busy === mod.id; return <article className="mod-management-card" key={mod.id}><div className="mod-management-card-main"><strong>{mod.name}</strong><small>{mod.id}{mod.system ? ' · Core' : ''}</small><div className="mod-management-meta"><span className={`mod-status ${installed ? 'installed' : ''}`}>{mod.status || 'available'}</span>{installed && <span className={`mod-status ${mod.enabled ? 'enabled' : 'disabled'}`}>{mod.enabled ? 'Enabled' : 'Disabled'}</span>}{mod.version && <span>Current {mod.version}</span>}{mod.latestVersion && <span>Latest {mod.latestVersion}</span>}</div>{mod.reason && <p>{mod.reason}</p>}</div><div className="mod-management-actions">{installed ? <><button className="secondary" type="button" disabled={busy !== null || !mod.updateAvailable} onClick={() => void run(mod.id, modLifecyclePath(mod.id, 'install'), { method: 'POST', body: JSON.stringify({}) })}>{actionBusy ? 'Working…' : actionLabel(mod)}</button><button className="secondary" type="button" disabled={busy !== null} onClick={() => void run(mod.id, modLifecyclePath(mod.id, mod.enabled ? 'disable' : 'enable'), { method: 'POST', body: '{}' })}>{actionBusy ? 'Working…' : mod.enabled ? 'Disable' : 'Enable'}</button><button className="danger" type="button" disabled={busy !== null} onClick={() => void run(mod.id, modLifecyclePath(mod.id, 'uninstall'), { method: 'POST', body: '{}' })}> {actionBusy ? 'Working…' : 'Uninstall'}</button></> : <button className="primary" type="button" disabled={busy !== null || mod.canInstall === false} onClick={() => void run(mod.id, modLifecyclePath(mod.id, 'install'), { method: 'POST', body: JSON.stringify({}) })}>{actionBusy ? 'Working…' : 'Install'}</button>}</div></article>; })}</div>}</SettingSection>
    <SettingSection title="Mod sources"><p className="settings-description">Add a source URL for Core to refresh available mods.</p><div className="mod-source-add"><Field label="Source URL"><input value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} placeholder="https://example.invalid/mods.json" /></Field><button className="primary" type="button" disabled={!sourceUrl.trim() || busy !== null} onClick={addSource}>{busy === 'source' ? 'Adding…' : 'Add source'}</button></div><div className="setting-actions"><button className="secondary" type="button" disabled={busy !== null} onClick={() => void run('refresh', '/api/mod-management/refresh', { method: 'POST', body: '{}' })}>Refresh sources</button></div>{sources.length > 0 && <div className="mod-source-list">{sources.map(source => <div className="mod-source-card" key={source.id}><div><strong>{source.url}</strong><small>{source.status || 'unknown'}{source.error ? ` · ${source.error}` : ''}</small></div><button className="danger" type="button" disabled={busy !== null} onClick={() => void run(source.id, `/api/mod-management/sources/${encodeURIComponent(source.id)}`, { method: 'DELETE' })}>Remove</button></div>)}</div>}</SettingSection>
  </div>;
}
