import { useEffect, useMemo, useState } from 'react';
import { api } from '../../app/api';
import { Field, SettingSection } from './SettingsPrimitives';
import './retention.css';

type RetentionPolicy = { version?: number; enabled: boolean; traceMaxAgeDays: number | null; traceMaxBytes: number | null; intervalMinutes: number };
type RetentionState = { lastRunAt?: string | null; lastResult?: { counts?: { deleteTraces?: number; deleteTraceBytes?: number; traceBytes?: number }; deleted?: { traces?: number } } | null; lastError?: string | null; nextRunAt?: string | null };
type RetentionPlan = { counts?: { deleteTraces?: number; deleteTraceBytes?: number; traceBytes?: number } };
type RetentionResponse = { policy: RetentionPolicy; state: RetentionState; plan: RetentionPlan };
type CleanupResponse = RetentionResponse & { dryRun?: boolean; counts?: RetentionPlan['counts'] };

const emptyPolicy: RetentionPolicy = { enabled: false, traceMaxAgeDays: null, traceMaxBytes: null, intervalMinutes: 1440 };
const formatBytes = (value?: number | null) => { if (!value) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}`; };
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : '—';

export function RetentionSettings() {
  const [policy, setPolicy] = useState<RetentionPolicy>(emptyPolicy);
  const [state, setState] = useState<RetentionState>({});
  const [plan, setPlan] = useState<RetentionPlan>({});
  const [status, setStatus] = useState<'loading' | 'idle' | 'saving' | 'previewing' | 'running'>('loading');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const load = async () => { setStatus('loading'); setError(''); try { const result = await api<RetentionResponse>('/api/settings/retention'); setPolicy({ ...emptyPolicy, ...result.policy }); setState(result.state || {}); setPlan(result.plan || {}); } catch (cause) { setError(cause instanceof Error ? `Could not load retention settings: ${cause.message}` : 'Could not load retention settings.'); } finally { setStatus('idle'); } };
  useEffect(() => { void load(); }, []);

  const updateNumber = (key: 'traceMaxAgeDays' | 'traceMaxBytes' | 'intervalMinutes', value: string) => setPolicy((current) => ({ ...current, [key]: value === '' ? null : Number(value) }));
  const validationError = useMemo(() => policy.enabled && policy.traceMaxAgeDays == null && policy.traceMaxBytes == null ? 'Enable at least one limit before turning on managed cleanup.' : policy.intervalMinutes < 15 || policy.intervalMinutes > 10080 ? 'Cadence must be between 15 minutes and 7 days.' : '', [policy]);
  const save = async () => { if (validationError) { setError(validationError); return; } setStatus('saving'); setError(''); setNotice(''); try { const result = await api<RetentionResponse>('/api/settings/retention', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(policy) }); setPolicy({ ...emptyPolicy, ...result.policy }); setState(result.state || {}); setPlan(result.plan || {}); setNotice('Retention policy saved.'); } catch (cause) { setError(cause instanceof Error ? `Could not save retention policy: ${cause.message}` : 'Could not save retention policy.'); } finally { setStatus('idle'); } };
  const preview = async () => { if (validationError) { setError(validationError); return; } setStatus('previewing'); setError(''); setNotice(''); try { const result = await api<CleanupResponse>('/api/settings/retention/preview', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ policy }) }); setPlan({ counts: result.counts }); setNotice(`Preview: ${result.counts?.deleteTraces ?? 0} traces, ${formatBytes(result.counts?.deleteTraceBytes)} reclaimable.`); } catch (cause) { setError(cause instanceof Error ? `Could not preview retention cleanup: ${cause.message}` : 'Could not preview retention cleanup.'); } finally { setStatus('idle'); } };
  const runNow = async () => { setStatus('running'); setError(''); setNotice(''); try { const result = await api<CleanupResponse>('/api/settings/retention/run', { method: 'POST' }); setState(result.state || {}); setPlan({ counts: result.counts }); setNotice(`Cleanup complete: ${result.counts?.deleteTraces ?? 0} traces removed, ${formatBytes(result.counts?.deleteTraceBytes)} reclaimed.`); } catch (cause) { setError(cause instanceof Error ? `Could not run retention cleanup: ${cause.message}` : 'Could not run retention cleanup.'); } finally { setStatus('idle'); } };

  return <SettingSection title="Managed trace retention"><p className="settings-section-description">Automatically remove old or oversized trace data. Cleanup is disabled until you enable it and choose at least one limit.</p><label className="retention-enabled"><input type="checkbox" checked={policy.enabled} onChange={(event) => setPolicy((current) => ({ ...current, enabled: event.target.checked }))} /> Enable managed cleanup</label><div className="field-pair retention-fields"><Field label="Maximum age (days)"><input type="number" min="1" max="36500" value={policy.traceMaxAgeDays ?? ''} onChange={(event) => updateNumber('traceMaxAgeDays', event.target.value)} placeholder="No age limit" /></Field><Field label="Maximum storage (bytes)"><input type="number" min="1" value={policy.traceMaxBytes ?? ''} onChange={(event) => updateNumber('traceMaxBytes', event.target.value)} placeholder="No storage limit" /></Field><Field label="Run every (minutes)"><input type="number" min="15" max="10080" value={policy.intervalMinutes} onChange={(event) => updateNumber('intervalMinutes', event.target.value)} /></Field></div>{validationError && <p className="settings-request-error" role="alert">{validationError}</p>}<div className="retention-summary"><span>Planned now<strong>{plan.counts?.deleteTraces ?? 0} traces · {formatBytes(plan.counts?.deleteTraceBytes)}</strong></span><span>Last run<strong>{formatDate(state.lastRunAt)}</strong></span><span>Next run<strong>{policy.enabled ? formatDate(state.nextRunAt) : 'Disabled'}</strong></span><span>Last reclaimed<strong>{formatBytes(state.lastResult?.counts?.deleteTraceBytes)}</strong></span></div>{state.lastError && <p className="settings-request-error" role="alert">Last run failed: {state.lastError}</p>}{error && <p className="settings-request-error" role="alert">{error}</p>}{notice && <p className="retention-notice" role="status">{notice}</p>}<div className="retention-actions"><button className="secondary" type="button" onClick={preview} disabled={status !== 'idle'}>{status === 'previewing' ? 'Previewing…' : 'Preview cleanup'}</button><button className="secondary" type="button" onClick={runNow} disabled={status !== 'idle' || !policy.enabled}>{status === 'running' ? 'Running…' : 'Run now'}</button><button className="primary" type="button" onClick={save} disabled={status !== 'idle'}>{status === 'saving' ? 'Saving…' : 'Save policy'}</button></div></SettingSection>;
}
