import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ConfirmProvider, useConfirm } from '../../src/app/ConfirmDialog';
import { ImagePreview } from '../../src/app/ImagePreview';
import { DocumentTabs } from '../../src/app/AppChrome';
import { WorkspaceRail, AgentsPanel } from '../../src/features/workspace/WorkspaceRail';
import { RightRail, CodexAccounts } from '../../src/features/panels/RightRail';
import { AgentSidebarSettings } from '../../src/features/settings/AgentSidebarSettings';
import { ChatModelSelector } from '../../src/features/chat/ChatPage';
import { ChatComposerDialogs } from '../../src/features/chat/ChatComposerDialogs';
import { themes } from '../../src/app/usePersistedLayout';
import '../../src/app.css';
const agents = ['Ada','Bea'].map((name,index) => ({id:name.toLowerCase(),name,avatar:name[0],targetId:'local',activity:'Idle',context:0,files:[],provider:'Fixture provider',model:'model-a',effort:'off',temperature:.2,subagents:[{id:`child-${index}`,name:`${name} child`,avatar:'C',activity:'Idle'}]}));
const providers = [{id:'fixture',provider:'Fixture provider',models:['model-a','model-b']}];
const accounts = ['One','Two'].map(name => ({id:name,name,plan:'Fixture',status:'Active',used:20,reset:'Local only'}));
function Fixture() {
 const confirm = useConfirm(); const [result,setResult] = useState('No action'); const [selected,setSelected] = useState(agents[0]); const [stream,setStream] = useState(agents[0].id); const [expanded,setExpanded] = useState(new Set<string>()); const [session,setSession] = useState('planning'); const [dialog,setDialog] = useState(false); const [name,setName] = useState(''); const [tab,setTab] = useState('a'); const [left,setLeft] = useState(50); const [right,setRight] = useState(50); const [prefs,setPrefs] = useState({view:'regular' as const,order:agents.map(a=>a.id)}); const [ordered,setOrdered] = useState(accounts);
 const actions = <div><button onClick={() => { void confirm({title:'Delete fixture item?',message:'Nothing is sent to any API.',tone:'danger'}).then(ok=>setResult(`Delete: ${ok}`)); }}>Destructive confirmation</button><button onClick={() => { ['First','Second'].forEach(title => { void confirm({title,message:'Concurrent local request'}).then(ok=>setResult(previous=>`${previous}; ${title}: ${ok}`)); }); }}>Queue confirmations</button><p role="status">{result}</p><ImagePreview alt="Local sample" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='200'%3E%3Crect width='400' height='200' fill='teal'/%3E%3C/svg%3E" /><AgentSidebarSettings agents={agents as any} preferences={prefs} setPreferences={setPrefs as any}/></div>;
 return <><div className="cockpit"><header className="app-header"><label>Theme <select onChange={e=>document.documentElement.dataset.theme=e.target.value}>{themes.map(theme=><option key={theme}>{theme}</option>)}</select></label><span>Owned fixture — no API</span></header><WorkspaceRail collapsed={false} topPanel="agents" bottomPanel="agents" layout="divided" split={left} onSplitChange={setLeft} onExpand={()=>{}} onCollapse={()=>{}} onResizeSplit={()=>{}} renderPanel={()=> <AgentsPanel agents={agents as any} selectedStreamId={stream} expandedAgents={expanded} onToggleAgent={id=>setExpanded(previous=>{const next=new Set(previous);next.has(id)?next.delete(id):next.add(id);return next;})} onSelectAgent={agent=>{setSelected(agent as any);setStream(agent.id);}} onSelectSubagent={(_,id)=>setStream(id)}/>}/><main className="workspace"><DocumentTabs tabs={[{id:'a',kind:'file',label:'First'},{id:'b',kind:'file',label:'Second'}]} activeTabId={tab} onSelect={setTab} onClose={id=>setResult(`Closed ${id}`)}/><ChatModelSelector selected={selected as any} savedProviders={providers as any} updateAgent={patch=>setSelected(previous=>({...previous,...patch}))} sessions={[{id:'planning'},{id:'review'}] as any} sessionId={session} onSessionChange={setSession} onNewSession={()=>setResult('Reset local session')} onNewNamedSession={()=>setDialog(true)} onCreateGroup={()=>setResult('Local group action')}/><div className="page-view">{actions}<p>Selected stream: {stream}; session: {session}; tabs: {tab}; splits: {left}/{right}</p><div className="profile-document-selector"><button className="active">Selected profile</button><button>Other profile</button></div><span className="forge-status queued">Queued</span><p className="hint">Wizard hint</p><label className="group-participant"><input type="checkbox"/>Participant</label><div className="group-agent" style={{margin:'20px'}}><span>A</span><button className="group-cancel" aria-label="Stop fixture run" onClick={()=>setResult('Stopped local run')}>×</button></div></div></main><RightRail collapsed={false} topPanel="codex" bottomPanel="codex" layout="divided" split={right} onSplitChange={setRight} onExpand={()=>{}} onCollapse={()=>{}} onResizeSplit={()=>{}} renderPanel={()=> <CodexAccounts accounts={ordered as any} onReorder={(source,target)=>setOrdered(previous=>{const next=[...previous];const from=next.findIndex(a=>a.id===source),to=next.findIndex(a=>a.id===target);next.splice(to,0,next.splice(from,1)[0]);return next;})}/>}/><footer className="status-bar">Fixture only — connect-src none</footer></div><ChatComposerDialogs agents={agents as any} session={{isOpen:dialog,isCreating:false,name,error:'',close:()=>setDialog(false),setName,create:async()=>{setResult(`Created ${name}`);setDialog(false);}}} group={{isOpen:false,isCreating:false,name:'',setName:()=>{},agentIds:[],error:'',close:()=>{},toggleAgent:()=>{},create:async()=>{},targetId:'local',rooms:[],roomsLoading:false,roomsError:'',openExisting:()=>{}}}/></>;
}
createRoot(document.getElementById('root')!).render(<ConfirmProvider><Fixture/></ConfirmProvider>);
