import { act, renderHook } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { apiForTarget } from './api';
import { useModelSelectionWriter } from './useModelSelectionWriter';
import type { Agent, SavedProvider } from './types';
vi.mock('./api', () => ({ apiForTarget: vi.fn() }));
it('serializes rapid intents, merges patches and ignores old acknowledgements', async () => {
 const target={id:'local',name:'Local',baseUrl:'',enabled:true};
 const agent={id:'a',provider:'Fixture',model:'one',effort:'low',temperature:0.2} as Agent;
 const provider={id:'p',provider:'Fixture',models:['one','two']} as SavedProvider;
 let release!: (value: unknown)=>void;
 vi.mocked(apiForTarget).mockImplementationOnce(()=>new Promise(resolve=>release=resolve)).mockResolvedValueOnce({selection:{model:'two',reasoningEffort:'low',temperature:0.9}});
 const commit=vi.fn(), report=vi.fn();
 const {result}=renderHook(()=>useModelSelectionWriter([target],[provider],commit,report));
 let pending!:Promise<void>;
 act(()=>{pending=result.current(agent,{temperature:0.1});});
 await act(async()=>{await result.current(agent,{temperature:0.9});await result.current(agent,{model:'two'});});
 expect(apiForTarget).toHaveBeenCalledTimes(1);
 await act(async()=>{release({selection:{model:'one',reasoningEffort:'low',temperature:0.1}});await pending;});
 expect(apiForTarget).toHaveBeenCalledTimes(2);
 expect(JSON.parse(vi.mocked(apiForTarget).mock.calls[1][2]!.body as string)).toMatchObject({model:'two',temperature:0.9});
 expect(commit).toHaveBeenCalledTimes(1);expect(commit).toHaveBeenCalledWith('a',expect.objectContaining({model:'two',temperature:0.9}));expect(report).not.toHaveBeenCalled();
});
