export function createObservabilityRoutes({ readJsonBody, sendJson, validateBoundaryBody, runtimeStatus, runtimeMetrics, codexLbAccounts, anthropicOauthUsage, openaiOauthUsage, currentActiveChatRunSummaries, selectedAgentRuntime, resolveAgentRuntime, listWorkspaceFiles, readWorkspaceFile, writeWorkspaceFile, listTraces, runtimeConfig, traceRootForRun, summarizeTrace, authorityExplanationFromTraceSummary, projectRoot } = {}) {
  return async function handleObservabilityRoute({ req, res, url } = {}) {
    if (req.method === 'GET' && url.pathname === '/api/codex-lb/accounts') { const result = await codexLbAccounts(); sendJson(res, result.ok ? 200 : (result.status || 500), result); return true; }
    if (req.method === 'GET' && url.pathname === '/api/anthropic/oauth/usage') { const result = await anthropicOauthUsage({ connectionId: url.searchParams.get('connectionId') || '', force: url.searchParams.get('force') === 'true' }); sendJson(res, result.ok ? 200 : (result.status || 500), result); return true; }
    if (req.method === 'GET' && url.pathname === '/api/openai/oauth/usage') { const result = await openaiOauthUsage({ connectionId: url.searchParams.get('connectionId') || '', force: url.searchParams.get('force') === 'true' }); sendJson(res, result.ok ? 200 : (result.status || 500), result); return true; }
    if (req.method === 'GET' && (url.pathname === '/api/health' || url.pathname === '/api/status')) { sendJson(res, 200, await runtimeStatus(url.searchParams.get('agentId'))); return true; }
    if (req.method === 'GET' && url.pathname === '/api/metrics') { sendJson(res, 200, await runtimeMetrics()); return true; }
    if (req.method === 'GET' && url.pathname === '/api/chat/runs/active') { sendJson(res, 200, { ok: true, runs: currentActiveChatRunSummaries({ agentId: url.searchParams.get('agentId'), sessionId: url.searchParams.get('sessionId') }) }); return true; }
    if (req.method === 'GET' && url.pathname === '/api/workspace/files') { const agentRuntime = await selectedAgentRuntime(url.searchParams.get('agentId')); sendJson(res, 200, await listWorkspaceFiles({ scope: url.searchParams.get('scope') || 'workspaces', agentRuntime })); return true; }
    if (req.method === 'GET' && url.pathname === '/api/workspace/file') { const agentRuntime = await selectedAgentRuntime(url.searchParams.get('agentId')); const result = await readWorkspaceFile(url.searchParams.get('path'), url.searchParams.get('scope') || 'workspaces', agentRuntime); sendJson(res, result.ok ? 200 : (result.status || 500), result); return true; }
    if (req.method === 'POST' && url.pathname === '/api/workspace/file') { const body = validateBoundaryBody('workspace-write', await readJsonBody(req)); const result = await writeWorkspaceFile(body, await selectedAgentRuntime(body.agentId)); sendJson(res, result.ok ? 200 : (result.status || 500), result); return true; }
    if (req.method === 'GET' && url.pathname === '/api/traces') { const agentRuntime = await resolveAgentRuntime(url.searchParams.get('agentId')); sendJson(res, 200, { ok: true, traces: await listTraces(url.searchParams.get('sessionId') || 'default', agentRuntime.agentId) }); return true; }
    if (req.method === 'GET' && url.pathname.startsWith('/api/traces/') && url.pathname.endsWith('/authority')) { const runId = decodeURIComponent(url.pathname.slice('/api/traces/'.length, -'/authority'.length)); const runtime = await runtimeConfig(); const sessionId = url.searchParams.get('sessionId') || 'default'; const agentRuntime = await resolveAgentRuntime(url.searchParams.get('agentId')); const trace = await summarizeTrace({ rootDir: await traceRootForRun({ rootDir: agentRuntime.agentWorkspaceRoot, sessionId, runId, runtime, agentId: agentRuntime.agentId }), runId, includeToolOutput: false }); sendJson(res, 200, { ok: true, runId, authority: authorityExplanationFromTraceSummary(trace) }); return true; }
    if (req.method === 'GET' && url.pathname.startsWith('/api/traces/')) { const runId = decodeURIComponent(url.pathname.slice('/api/traces/'.length)); const runtime = await runtimeConfig(); const sessionId = url.searchParams.get('sessionId') || 'default'; const agentRuntime = await resolveAgentRuntime(url.searchParams.get('agentId')); sendJson(res, 200, { ok: true, trace: await summarizeTrace({ rootDir: await traceRootForRun({ rootDir: agentRuntime.agentWorkspaceRoot, sessionId, runId, runtime, agentId: agentRuntime.agentId }), runId, includeToolOutput: url.searchParams.get('output') === 'true' }) }); return true; }
    return false;
  };
}
